### ISSUE TITLE
Create email functionality to email results of the web scrape

### ISSUE THREAD

**Issue by will62185** [will62185/web-scraper#7]
As an example this can look something like this:

```python
import smtplib
import datetime
import os
from sys import argv

# Instead of these values being hardcoded that can be set at runtime via argv
TO = "{User-email}"
SUBJECT = "Check out these service specials"
TEXT = "Web Scrape results go here"

# Email sign in, in this case gmail
# Ideally these will be environment variables
gmail_sender = "{email@gmail.com}"
gmail_passwd = "{email password}"

server = smtplib.SMTP("smtp.gmail.com", 587)
server.ehlo()
server.starttls()
server.login(gmail_sender, gmail_passwd)

BODY = "\r\n".join(["To: %s" % TO,
                               "From: %s" % gmail_sender"
                                "Subject: %s" % SUBJECT,
                                " ", TEXT])

try:
    server.sendmail(gmail_sender, [TO], BODY)
    print("Email was successfully sent")
except:
    print("Email failed to send yo")

server.quit()

**Comment by Volence** [comment]
Hey I just did something recently for a form for someone, could I take this? You want the user to type in the 'to' email field? Anything else? Do you have a gmail account that will be used for this by default? Anything else to know about this?

**Comment by will62185** [comment]
Hi @Volence, sure you can take this one. I was thinking for a first pass 'to' can be hardcoded since it will probably be a static value. For the gmail account info, it would be good to have it be environment variables us os the library.

**Comment by Volence** [comment]
Hi there! Just added all three to the environment variables just to prevent any spam or anything. Let me know if you get a chance to check it out and if it's alright! I was using gmail so I have it set up to use gmail's server currently, if you have a gmail account you're going to be using you just need to make sure that it has the correct settings.

**Comment by will62185** [comment]
@Volence cool! Let me check it out and I'll follow up with you soon 😄 .
